---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - concrete5::default
    attributes:
        mysql:
            server_debian_password: "1111"
            server_root_password:   "1111"
            server_repl_password:   "1111"
  - name: apache
    run_list:
      - apt::default
      - concrete5::apache2
  - name: swapon
    run_list:
      - test_swapon::micro
      - concrete5::default
    attributes:
        mysql:
            server_debian_password: "1111"
            server_root_password:   "1111"
            server_repl_password:   "1111"
